/*
 * file for __VERIFIER_nondet_int.c
 */

//  P() {0==-1}

//
//     This module was automatically generated by PIPS
//

//  P() {0==-1}

int __VERIFIER_nondet_int();

//  P() {}

int __VERIFIER_nondet_int()
{
}
