//
//     This module was automatically generated by PIPS and should
//     be updated by the user with READ and WRITE effects on
//     formal parameters to be useful...
//
int __VERIFIER_nondet_int()
{}
