
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package org.sosy_lab.cpachecker.cpa.automaton;

/** CUP generated interface containing symbol constants. */
public interface AutomatonSym {
  /* terminals */
  public static final int STRING_LITERAL = 42;
  public static final int STATE = 17;
  public static final int SQUAREEXPR = 44;
  public static final int ASSUME = 24;
  public static final int MINUS = 39;
  public static final int ASSERT = 23;
  public static final int MATCH = 25;
  public static final int SEMICOLON = 6;
  public static final int AND = 3;
  public static final int USEALL = 45;
  public static final int EVAL = 28;
  public static final int OR = 4;
  public static final int OPEN_BRACKETS = 9;
  public static final int COMMA = 7;
  public static final int CURLYEXPR = 43;
  public static final int PLUS = 38;
  public static final int EXIT = 20;
  public static final int EXCLAMATION = 2;
  public static final int IS_TARGET_STATE = 48;
  public static final int INITIAL = 16;
  public static final int EOF = 0;
  public static final int TRUE = 40;
  public static final int error = 1;
  public static final int EQEQ = 37;
  public static final int CHECK = 27;
  public static final int NEQ = 35;
  public static final int TARGET = 47;
  public static final int BREAK = 22;
  public static final int OBSERVER = 12;
  public static final int AUTOMATON = 11;
  public static final int EQ = 36;
  public static final int ERROR = 18;
  public static final int ARROW = 5;
  public static final int COLON = 8;
  public static final int ENTRY = 21;
  public static final int STOP = 19;
  public static final int GOTO = 32;
  public static final int MODIFY = 29;
  public static final int USEFIRST = 46;
  public static final int END = 14;
  public static final int CLOSE_BRACKETS = 10;
  public static final int LOCAL = 15;
  public static final int FALSE = 41;
  public static final int LABEL = 26;
  public static final int PRINT = 31;
  public static final int DO = 30;
  public static final int CONTROL = 13;
  public static final int INTEGER_LITERAL = 34;
  public static final int IDENTIFIER = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMATION",
  "AND",
  "OR",
  "ARROW",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "OPEN_BRACKETS",
  "CLOSE_BRACKETS",
  "AUTOMATON",
  "OBSERVER",
  "CONTROL",
  "END",
  "LOCAL",
  "INITIAL",
  "STATE",
  "ERROR",
  "STOP",
  "EXIT",
  "ENTRY",
  "BREAK",
  "ASSERT",
  "ASSUME",
  "MATCH",
  "LABEL",
  "CHECK",
  "EVAL",
  "MODIFY",
  "DO",
  "PRINT",
  "GOTO",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "NEQ",
  "EQ",
  "EQEQ",
  "PLUS",
  "MINUS",
  "TRUE",
  "FALSE",
  "STRING_LITERAL",
  "CURLYEXPR",
  "SQUAREEXPR",
  "USEALL",
  "USEFIRST",
  "TARGET",
  "IS_TARGET_STATE"
  };
}

