
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package org.sosy_lab.cpachecker.util.predicates.precisionConverter;

/** CUP generated interface containing symbol constants. */
public interface FormulaSymbols {
  /* terminals */
  public static final int DECLAREFUN = 2;
  public static final int DECIMAL = 7;
  public static final int SYMBOL = 5;
  public static final int LPAR = 8;
  public static final int EOF = 0;
  public static final int NUMERAL = 6;
  public static final int error = 1;
  public static final int ASSERT = 4;
  public static final int DEFINEFUN = 3;
  public static final int RPAR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECLAREFUN",
  "DEFINEFUN",
  "ASSERT",
  "SYMBOL",
  "NUMERAL",
  "DECIMAL",
  "LPAR",
  "RPAR"
  };
}

